/* 93. 西洋近代（17〜19世紀） */
window.DB_93 = {
  section:"93", title:"西洋近代", type:"O", color:"#c84080",
  entries:[
    {id:"93-1",典籍:"デカルト『方法序説』",章句:"我思う、ゆえに我あり",出典ID:"Disc. IV",
     原文:"cogito, ergo sum",
     訳文:"我思う、ゆえに我あり。",主題:"cogito・確実性",cats:[8]},
    {id:"93-2",典籍:"デカルト『省察』",章句:"明晰判明",出典ID:"Med. III",
     原文:"clare et distincte percipere",
     訳文:"明晰かつ判明に知覚すること（が真理の基準だ）。",主題:"真理・明証性",cats:[8]},
    {id:"93-3",典籍:"スピノザ『エチカ』",章句:"神即自然",出典ID:"Ethics I, Def. 6",
     原文:"Deus sive Natura",
     訳文:"神すなわち自然。",主題:"汎神論・神即自然",cats:[8]},
    {id:"93-4",典籍:"スピノザ『エチカ』",章句:"自由とは何か",出典ID:"Ethics I, Def. 7",
     原文:"Ea res libera dicitur, quae ex sola suae naturae necessitate existit",
     訳文:"自己の本性の必然性のみから存在し、行動する者が自由と呼ばれる。",主題:"自由・本性",cats:[8,7]},
    {id:"93-5",典籍:"ライプニッツ",章句:"モナド",出典ID:"Monadology §1",
     原文:"Les Monades, dont je vais parler, ne sont autre chose qu'une substance simple",
     訳文:"私が述べようとするモナドとは、単純な実体に他ならない。",主題:"モナド・実体",cats:[8]},
    {id:"93-6",典籍:"ロック『人間知性論』",章句:"白紙（タブラ・ラサ）",出典ID:"ECHU II:1",
     原文:"the mind is as a white paper void of all characters",
     訳文:"心はあらゆる文字の書かれていない白紙だ。",主題:"経験論・認識論",cats:[8]},
    {id:"93-7",典籍:"ヒューム『人間本性論』",章句:"理性は感情の奴隷",出典ID:"Treatise II:3",
     原文:"Reason is, and ought only to be the slave of the passions",
     訳文:"理性は、感情の奴隷であり、奴隷であるべきだ。",主題:"感情・理性",cats:[8]},
    {id:"93-8",典籍:"カント『純粋理性批判』",章句:"コペルニクス的転回",出典ID:"KrV Bxvi",
     原文:"daß wir nämlich von den Gegenständen nur das a priori erkennen, was wir selbst in sie legen",
     訳文:"我々が対象について先験的に認識できるのは、我々自身が対象に持ち込んだものだけだ。",主題:"認識論・コペルニクス的転回",cats:[8]},
    {id:"93-9",典籍:"カント『道徳形而上学の基礎づけ』",章句:"定言命法",出典ID:"GMM 421",
     原文:"Handle nur nach derjenigen Maxime, durch die du zugleich wollen kannst, daß sie ein allgemeines Gesetz werde",
     訳文:"あなたの格率が普遍的な法則となることを同時に意志できるような格率によってのみ行為せよ。",主題:"定言命法・義務",cats:[7,8]},
    {id:"93-10",典籍:"カント『実践理性批判』",章句:"道徳法則と星空",出典ID:"KpV 161",
     原文:"Der bestirnte Himmel über mir und das moralische Gesetz in mir",
     訳文:"私の上なる星の輝く空と、私の内なる道徳法則。",主題:"道徳・崇高",cats:[8,9]},
    {id:"93-11",典籍:"ヘーゲル『精神現象学』",章句:"精神は自己を知る",出典ID:"PhG §166",
     原文:"Der Geist ist das Wesen, das sich selbst betrachtet",
     訳文:"精神とは自己を見る本質である。",主題:"精神・弁証法",cats:[8]},
    {id:"93-12",典籍:"ヘーゲル『法の哲学』",章句:"現実的なものは理性的",出典ID:"RPh §10",
     原文:"Was vernünftig ist, das ist wirklich; und was wirklich ist, das ist vernünftig.",
     訳文:"理性的なものは現実的であり、現実的なものは理性的である。",主題:"弁証法・歴史",cats:[8,6]},
    {id:"93-13",典籍:"ショーペンハウアー『意志と表象としての世界』",章句:"意志と表象",出典ID:"WWV I §1",
     原文:"Die Welt ist meine Vorstellung.",
     訳文:"世界は私の表象である。",主題:"意志・表象・世界観",cats:[8]},
    {id:"93-14",典籍:"ショーペンハウアー",章句:"意志の否定",出典ID:"WWV I §68",
     原文:"die Verneinung des Willens zum Leben",
     訳文:"生への意志の否定。",主題:"意志の否定・解脱",cats:[8,9]},
    {id:"93-15",典籍:"ニーチェ『ツァラトゥストラ』",章句:"神は死んだ",出典ID:"GS 125",
     原文:"Gott ist tot! Gott bleibt tot! Und wir haben ihn getötet!",
     訳文:"神は死んだ！神は死んだままだ！そして我々が神を殺したのだ！",主題:"ニヒリズム・価値転換",cats:[8,0]},
    {id:"93-16",典籍:"ニーチェ『ツァラトゥストラ』",章句:"超人",出典ID:"Z Vorrede §3",
     原文:"Ich lehre euch den Übermenschen. Der Mensch ist etwas, das überwunden werden soll.",
     訳文:"私は超人を教える。人間は超えられるべきものだ。",主題:"超人・自己超克",cats:[7,8]},
    {id:"93-17",典籍:"ニーチェ『権力への意志』",章句:"永遠回帰",出典ID:"WM §1067",
     原文:"Das Leben — das ist eine ewige Wiederkunft.",
     訳文:"生とは永遠の回帰だ。",主題:"永遠回帰・運命愛",cats:[8,2]},
    {id:"93-18",典籍:"マルクス『資本論』",章句:"資本蓄積",出典ID:"Kapital I §24",
     原文:"Akkumuliert! Akkumuliert! Das ist Moses und die Propheten!",
     訳文:"蓄積せよ！蓄積せよ！それがモーセと預言者たちだ！",主題:"資本・経済批判",cats:[5,6]},
    {id:"93-19",典籍:"マルクス『共産党宣言』",章句:"歴史の動力",出典ID:"CM §1",
     原文:"Die Geschichte aller bisherigen Gesellschaft ist die Geschichte von Klassenkämpfen.",
     訳文:"これまでのあらゆる社会の歴史は、階級闘争の歴史だ。",主題:"歴史・階級",cats:[6,4]},
    {id:"93-20",典籍:"ダーウィン『種の起源』",章句:"自然選択",出典ID:"Origin §4",
     原文:"Natural Selection: its power compared with man's selection",
     訳文:"自然選択：人為選択と比較したその力。",主題:"自然選択・進化",cats:[8]},
    {id:"93-21",典籍:"ニュートン",章句:"神の目に見えない手",出典ID:"Principia Scholium",
     原文:"This most beautiful system of the sun, planets and comets could only proceed from the counsel and dominion of an intelligent and powerful Being.",
     訳文:"この太陽・惑星・彗星の最も美しい体系は、知性ある強力な存在の助言と支配からのみ生じ得た。",主題:"自然神学・秩序",cats:[8,6]},
    {id:"93-22",典籍:"ガリレオ",章句:"それでも動く",出典ID:"伝承",
     原文:"Eppur si muove.",
     訳文:"それでも（地球は）動く。",主題:"真理・抵抗",cats:[8]},
    {id:"93-23",典籍:"パスカル『パンセ』",章句:"考える葦",出典ID:"Pensées §200",
     原文:"L'homme n'est qu'un roseau, le plus faible de la nature, mais c'est un roseau pensant.",
     訳文:"人間は自然の中でもっとも弱い葦に過ぎない。しかし、考える葦だ。",主題:"人間・思考・尊厳",cats:[8,9]},
    {id:"93-24",典籍:"パスカル『パンセ』",章句:"賭け",出典ID:"Pensées §233",
     原文:"Dieu est, ou il n'est pas.",
     訳文:"神はいるか、いないか。",主題:"パスカルの賭け・信仰",cats:[8]},
    {id:"93-25",典籍:"ルソー『社会契約論』",章句:"人民主権",出典ID:"SC I:6",
     原文:"La souveraineté ne peut être représentée.",
     訳文:"主権は代表されることができない。",主題:"人民主権・民主主義",cats:[6,4]},
    {id:"93-26",典籍:"ルソー『エミール』",章句:"自然に従え",出典ID:"Emile I",
     原文:"Tout est bien sortant des mains de l'Auteur des choses: tout dégénère entre les mains de l'homme.",
     訳文:"万物は造物主の手から出るとき善いが、人間の手に渡るとき堕落する。",主題:"自然・教育",cats:[8,3]},
    {id:"93-27",典籍:"ヴォルテール",章句:"庭を耕せ",出典ID:"Candide §30",
     原文:"il faut cultiver notre jardin",
     訳文:"我々は自分たちの庭を耕さなければならない。",主題:"実践・現実",cats:[7,5]},
    {id:"93-28",典籍:"ジョン・スチュアート・ミル『功利主義』",章句:"最大多数の最大幸福",出典ID:"Utilitarianism §2",
     原文:"The greatest happiness of the greatest number",
     訳文:"最大多数の最大幸福。",主題:"功利主義・幸福",cats:[9,6]},
    {id:"93-29",典籍:"ジョン・スチュアート・ミル『自由論』",章句:"自由の原理",出典ID:"On Liberty §1",
     原文:"The only purpose for which power can be rightfully exercised over any member of a civilised community is to prevent harm to others.",
     訳文:"文明社会の成員に対して権力を行使できる唯一の目的は、他者への危害を防ぐことだ。",主題:"自由・権力",cats:[6,4]},
    {id:"93-30",典籍:"フランシス・ベーコン",章句:"知は力なり",出典ID:"Novum Organum I:3",
     原文:"Scientia est potentia.",
     訳文:"知識は力である。",主題:"知識・実践",cats:[8,5]},
    {id:"93-31",典籍:"ハーバート・スペンサー",章句:"適者生存",出典ID:"Principles of Biology §165",
     原文:"survival of the fittest",
     訳文:"適者生存。",主題:"進化・競争",cats:[8,6]},
    {id:"93-32",典籍:"ウィリアム・ジェームズ",章句:"真理は有用",出典ID:"Pragmatism §2",
     原文:"The true is the name of whatever proves itself to be good in the way of belief.",
     訳文:"真であるとは、信念の仕方において善いと証明されるものの名である。",主題:"プラグマティズム・真理",cats:[8]},
    {id:"93-33",典籍:"ジョン・デューイ",章句:"経験と教育",出典ID:"Democracy and Education §1",
     原文:"Education is not preparation for life; education is life itself.",
     訳文:"教育は生のための準備ではなく、教育そのものが生である。",主題:"教育・経験",cats:[7,3]},
    {id:"93-34",典籍:"スウェーデンボルグ",章句:"天界と地界の対応",出典ID:"Heaven and Hell §87",
     原文:"All things in the natural world correspond to spiritual things.",
     訳文:"自然界のすべての事物は、霊的事物に対応している。",主題:"照応・神秘主義",cats:[8,9]},
    {id:"93-35",典籍:"エマーソン",章句:"自己信頼",出典ID:"Self-Reliance §1",
     原文:"Trust thyself: every heart vibrates to that iron string.",
     訳文:"自分を信頼せよ。すべての心は、その鉄の弦に共鳴する。",主題:"自己信頼・個人主義",cats:[7,9]},
    {id:"93-36",典籍:"ソローの日記",章句:"単純に生きよ",出典ID:"Walden §2",
     原文:"Simplicity, simplicity, simplicity!",
     訳文:"単純に、単純に、単純に！",主題:"単純・自然生活",cats:[7,9]}
  ]
};
